### PR TITLE
ClojureBridge London curriculum

### PR DESCRIPTION
**Pull request by jr0cket**
We have been using Maria.cloud for ClojureBridge London since last year and
evolved the curriculum to include the most valuable aspects from several
curriculum's in one place and some more examples and challenges.  This provides a single page to work through for the students during the day.

Would this be a welcome addition to the curriculum's already available via
Maria.cloud directly?

Currently we ask students to fork a this proposed curriculum from a Gist to
their own GitHub account, where they can then access that Gist once they login
to Maria.cloud.

https://clojurebridgelondon.github.io/workshop/colours-and-shapes/

It would be a simpler process if the ClojureBridgeLondon curriculum was included
in Maria.cloud directly.  However, I appreciate you have a particular style you
wish to maintain, so if it does not fit along with the existing curriculum's
then we understand.

### CODE REVIEW

**Comment by daveliepmann** [comment]
Thanks, I'll try to carve out some time to give this a thorough read in the next week or so. We're excited that you're getting good mileage out of the project and hopefully we can do something on our end to make things smoother for you folks.

**Comment by daveliepmann** [comment]
I see we're under a bit of time pressure with your next workshop towards the end of this month. Would it be helpful to use a workflow that relies on the `Duplicate` button (in the upper-left controls on maria.cloud, it's the right-most link/button, next to `Revert`)? This might streamline your process as a stopgap measure while we figure out the ideal way to fully integrate your curriculum.

For example, I'm logged into GitHub on maria.cloud, and go to the London ClojureBridge URL you provide. I click `Duplicate` and after a moment (with a blue bar across the top showing progress) the page switches to https://gist.github.com/daveliepmann/98f901c6e89acac3f46a11ed531921b2, which is now my copy of the gist. Then I can make changes in maria.cloud, and either `Revert` back to what *my* gist has (which I can of course also change in the GitHub Gist editor) or `Save` directly from the maria.cloud UI into *my* gist.

**Comment by jr0cket** [comment]
Hello Dave,
Yes that all sound very reasonable.

If you can't do it in time, it's okay, we can manage.  But if you can do something this week then much appreciated.

Thank you.

**Comment by daveliepmann** [comment]
I've made a PR adding London CB's curriculum to the landing page and the Learning Modules list (left sidebar, behind the hamburger menu at top left). See https://github.com/mhuebert/maria/pull/225

**Comment by daveliepmann** [comment]
Regarding where the curriculum lives: we'd like you/London Clojurians/London ClojureBridge (as well as future other ClojureBridge groups with custom learning paths) to be able to maintain curricula without the need for commit privileges to this repo. Therefore what we've done is point `maria.cloud/cb-london` to the most recent version of the gist you provided. Hopefully that works for you.

If you'd rather track the curriculum in a repo you manage rather than a gist, we can handle that as well – just let us know.

You can see the new landing page (with "Events") and the inclusion of your curriculum in the "Learning Modules" list at https://dev.maria.cloud/ as we speak. The main production URL will have these changes soon.

**Comment by jr0cket** [comment]
Thank you Dave for all the work on this, it is much appreciated.   This looks a great approach and we will test it out this week.

I'll close this PR for now and get back to you if we have any issues.

Thanks again.

**Pull request closed without merging**
